version: '3.8'

services:
  my-database:
    image: christqnd2409/my-database:latest
    container_name: my-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-red

  my-backend:
    image: christqnd2409/my-backend:latest
    container_name: my-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://my-database:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: myuser
      QUARKUS_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - my-database
    networks:
      - my-red

  my-frontend:
    image: christqnd2409/my-frontend:latest
    container_name: my-frontend
    ports:
      - "4200:4200"
    depends_on:
      - my-backend
    networks:
      - my-red

volumes:
  pgdata:

networks:
  my-red:
